version: "3.3"
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 80:80
    expose:
      - 80
    restart: always
    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_NAME
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_TABLE_PREFIX
      - WORDPRESS_DEBUG
    # vstm: add shared volume
    volumes:
      - wp_data:/var/www/html

  wordpress-cli:
    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_NAME
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_TABLE_PREFIX
      - WORDPRESS_DB_USER
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    # vstm: This is required to run wordpress-cli with the same
    # user-id as wordpress. This way there are no permission problems
    # when running the cli
    user: xfs
    # vstm: The sleep 10 is required so that the command is run after
    # mysql is initialized. Depending on your machine this might take
    # longer or it can go faster.
    links:
      - db:mysql
#    command: >
#      /bin/sh -c '
#      sleep 10;
#      wp core install --path="/var/www/html" --url="http://localhost:80" --title="Local Wordpress By Docker" --admin_user=admin --admin_password=4HUYe3F5VPGRzVPPVj --admin_email=foo@bar.com
#      '
    # vstm: add shared volume
    volumes:
      - wp_data:/var/www/html

  webdav-client:
    environment:
      - WEBDRIVE_USERNAME
      - WEBDRIVE_PASSWORD
      - WEBDRIVE_URL
      - DAVFS2_ASK_AUTH
    build: ./davfs2/
    devices: 
      - "/dev/fuse:/dev/fuse"
    cap_add: 
      - SYS_ADMIN
    security_opt: 
      - apparmor:unconfined

    volumes:
      - mnt_data:/mnt/webdrive
      - wp_data:/var/www/html
    #to be able to copy backups to webdrive

volumes:
  db_data:
  # vstm: add shared volume
  wp_data:
  mnt_data:
